# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0006_remove_timeslot_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
