# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0003_auto_20171027_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
