# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171123_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='created',
            new_name='time',
        ),
    ]
