# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20171028_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='price',
        ),
    ]
