# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_remove_session_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(default='Booked', max_length=10),
        ),
    ]
