# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offering', '0007_timeslot_status'),
        ('booking', '0007_session_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='end',
        ),
        migrations.RemoveField(
            model_name='session',
            name='start',
        ),
        migrations.RemoveField(
            model_name='session',
            name='tutor',
        ),
        migrations.AddField(
            model_name='session',
            name='timeslot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslot', to='offering.Timeslot'),
        ),
    ]
