# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20171119_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
