# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20171123_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='transaction1',
        ),
        migrations.RemoveField(
            model_name='session',
            name='transaction2',
        ),
    ]
