# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_coupon'),
        ('booking', '0012_auto_20171123_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='transaction0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction0', to='transaction.Transaction'),
        ),
        migrations.AddField(
            model_name='session',
            name='transaction1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction1', to='transaction.Transaction'),
        ),
    ]
