# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20171123_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='transaction0',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction0', to='transaction.Transaction'),
        ),
        migrations.AlterField(
            model_name='session',
            name='transaction1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction1', to='transaction.Transaction'),
        ),
    ]
