# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_reset_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Private Tutor'), ('C', 'Contracted Tutor')], default='S', max_length=2),
        ),
    ]
