# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171110_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Private Tutor'), ('C', 'Contracted Tutor')], default='1', max_length=2),
        ),
    ]
