# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_auto_20171119_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorType', models.CharField(choices=[('P', 'Private Tutor'), ('C', 'Contracted Tutor')], default='P', max_length=2)),
                ('courses', models.TextField(blank=True)),
                ('biography', models.TextField(blank=True)),
                ('subjects', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='profile',
            name='identity',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Tutor')], default='S', max_length=2),
        ),
    ]
