# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20171119_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='tutorType',
            new_name='tutortype',
        ),
    ]
