# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='static/assets/img/avatar/def_avatar.png', upload_to='static/assets/img/avatar/'),
        ),
    ]
