# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='show_profile',
            field=models.BooleanField(default=True),
        ),
    ]
