# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 18:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_profile_picture'),
        ('home', '0019_tutorprofile_show_profile'),
    ]

    operations = [
    ]
